- .github/workflows/release-branch.yaml
> :bug:  update action version

- .goreleaser.yaml
> ✨ add go releaser config

- .goreleaser.yaml
> 🐛 update ci

- .goreleaser.yaml
> 🐛 update goreleaser config

- .github/workflows/goreleaser.yml
> 🐛  customize goreleaser

- .gitignore
- .goreleaser.yaml
> 🐛  update goreleaser with ko settings

- .goreleaser.yaml
> ✨ add ko repo

- .github/workflows/goreleaser.yml
- .goreleaser.yaml
> 🐛 fix release action with ko settings

- .goreleaser.yaml
> 🐛  update OCI repo in goreleaser

- .github/workflows/helm.yaml
> 🐛 fix helm package version

- .github/workflows/helm.yaml
> 🐛 update action versions for helm

- .github/workflows/helm.yaml
> 🐛  update action versions for helm

- .github/workflows/helm.yaml
> 🐛  test helm publish action

- .github/workflows/helm.yaml
> 🐛 test helm publish action

- .goreleaser.yaml
> ✨ add brew config to goreleaser

- .github/workflows/goreleaser.yml
- .goreleaser.yaml
> 🐛 clean up brew config

- Makefile
- README.md
- cmd/kflex/init/config.go
- cmd/kflex/init/init.go
- cmd/kflex/main.go
- docs/contributors.md
- docs/debugging.md
- pkg/helm/installer.go
- pkg/util/util.go
> ✨ update init to use the released operator image and chart

- kubeflex.rb
>  ✨ Brew formula for latest release

- .github/workflows/dco.yaml
> ✨ add dco check action

- .github/workflows/dco.yaml
- .github/workflows/pr-verifier.yaml
- .github/workflows/spellcheck_action.yml
> 🐛 add DCO action job name

- README.md
> 🐛 update README

- README.md
> ✨ add status badges

- sonar-project.properties
> ✨ remove unused config

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.1.1

- README.md
- cmd/cmupdate/main.go
- cmd/kflex/create/create.go
- cmd/kflex/main.go
- docs/users.md
> ✨ add user guide and fix minor issues

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.2.0

- pkg/reconcilers/k8s/deployment.go
> 🐛 allow control plane names with the "-" character

- pkg/reconcilers/ocm/reconciler.go
- pkg/reconcilers/shared/ingress.go
- pkg/reconcilers/vcluster/reconciler.go
- pkg/util/status_check.go
> 🐛  fix conditions updates for ocm and vcluster

- api/v1alpha1/controlplane_types.go
- config/crd/bases/tenancy.kflex.kubestellar.org_controlplanes.yaml
> ✨ add control plane type to additional printer columns

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.2.1

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.2.2

- docs/debugging.md
> ✨ update docs

- config/manager/config.yaml
Missing config for issue 84
Fixes #84
> :bug: add missing config

- kubeflex.rb
> Brew formula update for kubeflex version v0.2.3

- docs/users.md
Document new options for domain and external ingress port in kflex init.
Fixes #
> 📖  update docs for new options in kflex init

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.2.4

- docs/users.md
Document how to install KubeFlex on an existing cluster with nginx ingress and SSL passthru just using helm instead than the kubeflex CLI. 
Fixes #
> 📖 document install with helm

- config/rbac/role.yaml
- go.mod
- go.sum
- internal/controller/controlplane_controller.go
- pkg/reconcilers/k8s/deployment.go
- pkg/util/pg.go
- pkg/util/util.go
Adds finalizer and cleanup shared DB when control plane is deleted.
Fixes #95
> 🐛 cleanup shared DB when control plane is deleted

- docs/contributors.md
- docs/debugging.md
> 📖  minor refactoring of docs

- kubeflex.rb
> ✨   Brew formula update for kubeflex version v0.2.5

- chart/templates/operator.yaml
- cmd/kflex/init/config.go
- cmd/kflex/init/init.go
- config/rbac/role.yaml
- docs/users.md
- go.mod
- go.sum
- internal/controller/controlplane_controller.go
- pkg/client/client.go
- pkg/util/ocp.go
Fixes a few minor issues encountered on vcluster control plane types
>  📖 fixes for OpenShift support

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.2.5

- pkg/helm/installer.go
Fix helm local filesystem write permission when running in OpenShift.
> 🐛 fix helm permissions in ocp

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.2.6

- cmd/cmupdate/main.go
- cmd/manager/main.go
- internal/controller/controlplane_controller.go
- pkg/reconcilers/k8s/reconciler.go
- pkg/reconcilers/ocm/reconciler.go
- pkg/reconcilers/shared/job.go
- pkg/reconcilers/shared/rbac.go
- pkg/reconcilers/shared/reconciler.go
- pkg/reconcilers/vcluster/chart.go
- pkg/reconcilers/vcluster/reconciler.go
- pkg/reconcilers/vcluster/service.go
- pkg/util/status_check.go
- pkg/util/util.go
supports installing OCM in a vcluster control plane
Fixes #113
> ✨ supports installing OCM in a vcluster control plane

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.2.7

- config/samples/postcreate-hooks/ocm.yaml
- pkg/reconcilers/vcluster/reconciler.go
- pkg/reconcilers/vcluster/secret.go
add in-cluster kubeconfig to vcluster Kubeconfig secret. 
Fixes #119
> ✨ Add in-cluster kubeconfig to vcluster Kubeconfig secret

- config/builtin-hooks/ocm.yaml
Update built-in hook for ocm.
Fixes #
> 🐛 update built-in hook

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.3.0

- cmd/manager/main.go
- go.mod
- internal/controller/controlplane_controller.go
- pkg/reconcilers/shared/postcreate_hook.go
- pkg/util/clusterscoped_refs.go
Add owner refs to clusterscoped resources associated with cp
Fixes #136
> 🐛  add owner refs to clusterscoped resources associated with cp

- config/samples/postcreate-hooks/kslight.yaml
- config/samples/postcreate-hooks/ocm.yaml
- config/samples/postcreate-hooks/openshift-crds.yaml
- docs/users.md
- pkg/reconcilers/shared/postcreate_hook.go
Propagate labels from hooks to controlplanes.
Fixes #143
> ✨ propagate labels from hooks to controlplanes

- docs/contributors.md
> 📖  update contribs docs

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.3.2

- docs/users.md
> 📖 update users doc

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.3.3

- chart/templates/install-hooks.yaml
> 🐛 fix helm install built-in hooks rbac permissions

- docs/users.md
- pkg/util/unstructured.go
Fix util.GroupVersionKindToResource vs. stale api service error
Fixes #160
> 🐛 Fix util.GroupVersionKindToResource vs. stale api service error

- pkg/reconcilers/shared/postcreate_hook.go
- pkg/util/unstructured.go
> ✨ improve GVR to GVK conversions

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.4.0

- docs/users.md
document the 'host' control plane type
Fixes #171
> 🐛 document the 'host' control plane type

- cmd/kflex/create/create.go
- cmd/kflex/ctx/ctx.go
- cmd/kflex/delete/delete.go
- cmd/kflex/init/cluster/kind.go
- cmd/kflex/init/init.go
- cmd/kflex/main.go
- pkg/util/print.go
Added a chattyStatus flag to kflex.  Once this is merged, we'll update the kubestellar CICD to use the flag so we won't get spammed in the testing output.
Fixes #
> ✨ add chattyStatus flag

- pkg/reconcilers/k8s/deployment.go
Add pv-protection and pvc-protection controllers to k8s kube-controller manager
Fixes #179
> 🐛 add pv-protection and pvc-protection controllers to k8s kube-controller manager

- chart/templates/install-hooks.yaml
- cmd/kflex/create/create.go
- cmd/kflex/ctx/ctx.go
- cmd/kflex/delete/delete.go
- cmd/kflex/init/cluster/kind.go
- cmd/kflex/init/init.go
- cmd/kflex/main.go
- docs/users.md
- kubeflex.rb
- pkg/reconcilers/k8s/deployment.go
- pkg/util/print.go
> ✨ Release 0.4

- cmd/kflex/create/create.go
- cmd/kflex/ctx/ctx.go
- cmd/kflex/delete/delete.go
- cmd/kflex/init/init.go
- cmd/kflex/main.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/util/util.go
detect openshift first and warn on use of flag --create-kind
Fixes #186
> ✨ detect openshift first and warn on use of flag --create-kind

- Makefile
- docs/contributors.md
- docs/debugging.md
- pkg/reconcilers/ocm/chart.go
- pkg/reconcilers/shared/job.go
- pkg/util/print.go
move remaining private images from private to public kubestellar repos
Fixes #197
> 🐛 move remaining private images from private to public kubestellar repos

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.4.2

- pkg/helm/installer.go
use temp dir for repo config in helm installer
Fixes #203
> ✨ use temp dir for repo config in helm installer

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.4.3

- chart/templates/operator.yaml
- config/default/manager_auth_proxy_patch.yaml
- pkg/helm/installer.go
Fix a permission issue with helm cache config
Fixes #
> 🐛 update helm config settings

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.5.0

- docs/users.md
> 📖 document user-defined hook vars

- .github/workflows/test-e2e.yaml
- test/e2e/README.md
- test/e2e/cleanup.sh
- test/e2e/manage-type-k8s.sh
- test/e2e/manage-type-vcluster.sh
- test/e2e/run.sh
- test/e2e/setup-kubeflex.sh
- test/e2e/setup-shell.sh
- test/e2e/use-kubeflex.sh
This PR creates an initial set of e2e test for KubeFlex.
Part of #223
> ✨ Initial set of e2e tests

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.5.1

- .github/workflows/goreleaser.yml
Update go releaser action go version.
Fixes #
> 🐛 use go 1.22 in go releaser

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.6.1

- pkg/reconcilers/vcluster/chart.go
generate correctly TLS-SAN for HostContainer
Fixes #247
> 🐛 generate correctly TLS-SAN for HostContainer

- chart/templates/operator.yaml
- chart/values.yaml
- config/default/manager_auth_proxy_patch.yaml
Enable verbosity control from chart values
Fixes #
> ✨Enable verbosity control from chart values

- docs/users.md
This PR makes further updates to the user guide remarks about the way `kflex` remembers the name of the kubeconfig context used to access the hosting cluster. My previous update was not entirely accurate and clear. Also, I discovered a better way to recover the storage of that context name.
Fixes #
> 📖 Still more/better hosting context doc

- docs/users.md
improve docs for nginx ingress helm chart install 
Fixes #262
> 📖 improve docs for nginx ingress helm chart install

- pkg/kubeconfig/kubeconfig.go
wait for control plane kubeconfig secret to be created
Fixes #258
> 🐛 wait for control plane kubeconfig secret to be created

- cmd/kflex/ctx/ctx.go
- pkg/kubeconfig/kubeconfig.go
fix setting missing context for cp of type host
Fixes #260
> 🐛 fix setting missing context for cp of type host

- cmd/kflex/ctx/ctx.go
This PR adds detail to a couple of info messages.
Fixes #
> ✨ Slightly more informative messages

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.6.2

- .github/workflows/goreleaser.yml
Fixes issue with go releaser version:
```
GoReleaser latest installed successfully
/opt/hostedtoolcache/goreleaser-action/2.3.2/x64/goreleaser release --timeout 60m --clean
• only configurations files on version: 2 are supported, yours is version: 0, please update your configuration
⨯ release failed after 0s                  error=only configurations files on version: 2 are supported, yours is version: 0, please update your configuration
```
> 🐛 pin goreleaser version

- .goreleaser.yaml
Add header to go releaser file to fix version issue
> 🐛 more on pin goreleaser version

- .goreleaser.yaml
> 🐛  even more on pin goreleaser version

- kubeflex.rb
> ✨  Brew formula update for kubeflex version v0.6.3

- pkg/reconcilers/k8s/deployment.go
upgrade kube from 1.27 to 1.29
Fixes #286
> ✨ upgrade kube from 1.27 to 1.29

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.7.0

- pkg/kubeconfig/kubeconfig.go
Increase timeout for loadControlPlaneKubeconfig() from 5 to 15 minutes.
Fixes #291
> 🐛 increase timeout for loadControlPlaneKubeconfig()

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.7.1

- kubeflex.rb
This PR is the conclusion of the release process, for release 0.7.2.
Fixes #
> ✨  Brew formula update for kubeflex version v0.7.2

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.8.0

- docs/contributors.md
Update contributors doc to explain how to create a copy of postgresql chart and image on quay.io
Fixes #313
> 📖 Update contributors doc to explain how to create a copy of postgresql chart and image on quay.io

- chart/templates/operator.yaml
- cmd/kflex/init/config.go
- config/manager/kustomization.yaml
- config/samples/postcreate-hooks/postgres.yaml
- test/e2e/list-controller-pch.yaml
- test/e2e/manage-type-vcluster.sh
Removes remaining docker hub deps
> 🐛 remove remaining dockerhub dependencies

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.8.1

- kubeflex.rb
>  ✨ Brew formula update for kubeflex version v0.8.2

- cmd/kflex/init/cluster/kind.go
- test/e2e/setup-kubeflex.sh
upgrade NGINX controller to v1.12.1
Fixes #329
> 🐛  upgrade NGINX controller to v1.12.1

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.8.3

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.8.4

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.8.5

- kubeflex.rb
> ✨ Brew formula update for kubeflex version v0.8.6

- kubeflex.rb
This PR updates the brew formula to track release 0.8.7, as prescribed in https://github.com/kubestellar/kubeflex/blob/main/docs/contributors.md#steps-to-make-release (if I understand that correctly).
Fixes #
> ✨  Brew formula update for kubeflex version v0.8.7

- config/default/manager_auth_proxy_patch.yaml
This PR updates the reference to the kube-rbac-proxy container image, in the real source of the reference.
Fixes #
> ✨  Update the real source of the kube-rbac-proxy image ref

- kubeflex.rb
This PR updates brew for the 0.8.8 release.
Fixes #
> ✨  Brew update for 0.8.8 release

- OWNERS
- config/manager/kustomization.yaml
> ✨ add OWNERS file

- README.md
Resolve outdated instructions for brew install in README.md
> 🐛 update brew instructions in README.md

- Makefile
> 🐛In Makefile for add ko-local-build as dependency for installing a local chart 

- api/v1alpha1/controlplane_types.go
Add k3s control plane type
Fixes #403
> ✨ new(403): add k3s control plane type

- pkg/reconcilers/k3s/README.md
- pkg/reconcilers/k3s/apiserver.go
- pkg/reconcilers/k3s/service.go
- new: apiserver statefulset is defined
Write the skeleton (minimum viable) statefulset of k3s apiserver.
TODO:
- Define headless Service def
- Write deployment of StatefulSet and Service object to cluster
- Test that resources are working
Fixes #418
> ✨ new(418): write k3s apiserver resource def

- docs/architecture.md
- docs/postgresql-architecture-decision.md
> 📖 answer of why postgresql is a post create hook job

- pkg/kubeconfig/extensions.go
Implements CheckGlobalKubeflexExtension to check if the global kubeflex extension is set. 
redpinecube/kubeflex#7
Relates to #388
> ✨ feature : implement CheckGlobalKubeflexExtension

- cmd/kflex/config/config.go
- cmd/kflex/config/diagnose.go
- pkg/kubeconfig/extensions.go
- pkg/kubeconfig/extensions_test.go
Implements CheckHostingClusterContextName. 
Note : this PR should be reviewed after #458
redpinecube/kubeflex#11
#388
> ✨ feature : check if the hosting cluster context name is set

- pkg/reconcilers/k3s/ingress.go
- pkg/reconcilers/k3s/reconciler.go
✨ task: add ingress reconciler logic
Fixes #450
> ✨ task: add ingress reconciler logic

- pkg/reconcilers/k3s/apiserver.go
✨ task: improve and ref apiserver k3s code
Fixes #450
> ✨ task: improve and ref apiserver k3s code

- pkg/reconcilers/k3s/configdata.go
- pkg/reconcilers/k3s/embed/save-k3s-kubeconfig.sh
- testapi
Create the configmap manifest of k3s-scripts which contains the utility script that retrieves k3s kubeconfig file.
Fixes #472
> ✨new(472): add configmap new function

- pkg/util/status_check.go
- pkg/util/util.go
Fix k3s server status to Ready=True when server is ready to serve request.
Fixes #511
> 🐛 update status Ready=True when k3s server is ready

- OWNERS
> 🌱 add rxinui as maintainer

- pkg/kubeconfig/extensions.go
- pkg/kubeconfig/extensions_test.go
Implements : CheckExtensionInitialContextNameSet. 
#388 
redpinecube/kubeflex#26
> ✨ feature : check extensioninitialcontextname set

- pkg/kubeconfig/extensions_test.go
Implements : TestCheckExtensionInitialContextNameSetTrue
Note : Please review this PR after #500 
#388 
redpinecube/kubeflex#28
> 🌱 test : extensioninitialcontextnameset true

- .github/workflows/dco.yaml
update dco to skip check for dependabot
> 🌱 update dco to skip check for dependabot

- kflex.rb
Brew formula update for kubeflex version v0.9.1
> ✨ Brew formula update for kubeflex version v0.9.1

- nextra/README.MD
- nextra/content/README.MD
Very simple PR to create the folder structure for web documentation that the main Nextra.js-based site(s) will be using.
While the previously submitted and closed overview docs PR is being re-edited into smaller changes, this PR creates the subfolders needed for the site implementation and drops an explanatory README into the nextra subfolder.
Fixes #
> 📖 Creating nextra subfolder structure and README
