kubestellar/kubeflex

api/v1alpha1/conditions.go, api/v1alpha1/controlplane_types.go, cmd/cmupdate/main.go, cmd/kflex/create/create.go, cmd/kflex/init/cluster/kind.go, cmd/kflex/main.go, config/crd/bases/tenancy.kflex.kubestellar.org_controlplanes.yaml, config/samples/tenancy_v1alpha1_controlplane.yaml, docs/debugging.md, internal/controller/controlplane_controller.go, pkg/certs/kconfig_gen.go, pkg/kubeconfig/kubeconfig.go, pkg/reconcilers/k8s/deployment.go, pkg/reconcilers/k8s/reconciler.go, pkg/reconcilers/k8s/secret.go, pkg/reconcilers/k8s/service.go, pkg/reconcilers/ocm/chart.go, pkg/reconcilers/ocm/job.go, pkg/reconcilers/ocm/rbac.go, pkg/reconcilers/ocm/reconciler.go, pkg/reconcilers/ocm/service.go, pkg/reconcilers/shared/config.go, pkg/reconcilers/shared/ingress.go, pkg/reconcilers/shared/namespace.go, pkg/reconcilers/shared/reconciler.go, pkg/util/util.go
Adds support for open cluster management control plane. A control plane type can be added just specifying a type "com" in the control plane CR.
Fixes #56
=> ✨ add open cluster management control plane type

cmd/kflex/create/create.go, internal/controller/controlplane_controller.go, pkg/certs/kconfig_gen.go, pkg/kubeconfig/kubeconfig.go, pkg/reconcilers/k8s/reconciler.go, pkg/reconcilers/shared/ingress.go, pkg/reconcilers/vcluster/chart.go, pkg/reconcilers/vcluster/reconciler.go, pkg/util/util.go
Adds the support to create a vcluster control plane. With the vcluster control plane, users can create pods in the hosting cluster namespace allocated to the vcluster control plane.
Fixes # #55
=> ✨ add support for vcluster control planes

README.md, cmd/kflex/init/cluster/kind.go, docs/users.md
=> 🐛 fix issue-61 and improve docs

config/manager/kustomization.yaml, config/rbac/role.yaml, docs/debugging.md, internal/controller/controlplane_controller.go, pkg/reconcilers/vcluster/chart.go
=> 🐛 fix rbac permissions for vcluster and ocm control planes

pkg/reconcilers/k8s/deployment.go
This PR uses an improved address in the `--master` flag for the `kube-controller-manager` inside a controller plane of type `k8s`.
Before the change, the controller manager failed to verify x509 certificate.
```
E0726 15:41:22.225385       1 leaderelection.go:327] error retrieving resource lock kube-system/kube-controller-manager: Get "https://consumer0:9444/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager?timeout=5s": tls: failed to verify certificate: x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster, kubernetes.default.svc.cluster.local, localhost, kubeflex-control-plane, consumer0.consumer0-system, consumer0.consumer0-system.svc, consumer0.consumer0-system.svc.cluster, …
```
=> 🐛 Improve apiserver service name for controller manager

chart/templates/operator.yaml, chart/values.yaml, cmd/kflex/init/config.go, cmd/kflex/init/init.go, cmd/kflex/main.go, config/manager/kustomization.yaml, docs/debugging.md, pkg/certs/kconfig_gen.go, pkg/reconcilers/k8s/reconciler.go, pkg/reconcilers/k8s/secret.go, pkg/reconcilers/ocm/chart.go, pkg/reconcilers/ocm/reconciler.go, pkg/reconcilers/ocm/service.go, pkg/reconcilers/shared/config.go, pkg/reconcilers/shared/ingress.go, pkg/reconcilers/shared/reconciler.go, pkg/reconcilers/vcluster/chart.go, pkg/reconcilers/vcluster/reconciler.go, pkg/util/util.go
Allow to use config map to set configuration, for example allow to use existing cluster with different port mapping for ingress than default port 9443 and use a domain different than "localtest.me" 
Fixes #83
=> ✨ use ConfigMap to store KubeFlex configuration such as external port for ingress and domain

cmd/kflex/ctx/ctx.go, pkg/kubeconfig/kubeconfig.go
load cp kubeconfig context from server if not in local kubeconfig
Fixes #94
=> ✨ load cp kubeconfig context from server if not in local kubeconfig

chart/templates/install-hooks.yaml
This PR replaces #174. (Because I deleted the merging branch of #174 by mistake)
I pushed to `quay.io/kubestellar/kubectl:1.27.8` which is a multi-platform image for linux/amd64 and linux/arm64.
After merging this, do we need to update the chart ghcr.io/kubestellar/kubeflex/chart/kubeflex-operator, maybe overwrite the v0.4.0 tag? Because currently the chart refers to the ECR community image.
=> ✨ Use a multi-platform image in quay.io/kubestellar for kubectl

.github/workflows/goreleaser.yml
Add `--app-version` to the goreleaser packaging action
Fixes #
=> ✨ Add `--app-version` to the goreleaser packaging action

pkg/reconcilers/k8s/deployment.go
Upgrade kine image from v0.9.9-amd64 to v0.11.4 to allow kubeflex to run in linux/arm64
Fixes #
https://github.com/kubestellar/kubeflex/issues/189
=> 🐛 Upgrade kine image from v0.9.9-amd64 to v0.11.4

cmd/kflex/init/init.go, docs/users.md, pkg/util/ocp.go
Based on the merged #204, we can now remove the use of the anyuid SCC policy that was needed to run in OCP
Please test these changes one more time on a fresh OpenShift cluster.
Fixes #
=> ✨ Remove OCP anyuid SCC polocy

chart/templates/postgresql-hooks.yaml
Replace explicit `kubeflex-system` with `{{ .Release.Namespace }}`
Fixes #
=> ✨Remove explicit reference to kubeflex-system namespace

go.mod, go.sum
This PR fixes the go.mod to depend on the same release of k8s.io/apiserver as other kubernetes repos.
Fixes #
=> 🌱 Fix k8.sio/apiserver dependency to match others

chart/templates/postgresql.yaml
Force the use of `kubeflex-system` namespace for the `postgresql` deployment, idependently from the helm namespace.
This is to match `kubeflex-operator` behavior.
Fixes #
=> ✨Force kubeflex-system ns

.gitignore, cmd/kflex/create/create.go, pkg/kubeconfig/kubeconfig.go
Fixes bug for `kflex create wds2 -t host` fails but exits with status 0, when context wds2 pre-existing 
Fixes #238
=> 🐛 exit with non-zero error when context already exists

docs/users.md
Add clarification that `kflex create -p` does not wait for the PCH to "complete" in any sense to the user guide.
Fixes #237
=> 📖 add clarification on PCH behavior

chart/templates/postgresql.yaml
When installing the helm chart without specifying the `kubeflex-system` namespace, the `helm-install-rolebinding` is created in the default namespace instead of the `kubeflex-system` namespace. This causes the postgres installation to fail
Fixes #
=> 🐛 Fix postgres install hook role binding

chart/templates/operator.yaml, config/default/manager_auth_proxy_patch.yaml
Add initContainer to wait for postgresql Ready status.
This prevent kubeflex from acting on CP CRs before the database is ready
This dramatically speedup the creation of CPs and prevent crashes.
Fixes #
=> ✨Add initContainer to wait for postgresql Ready status

chart/values.yaml, config/default/manager_auth_proxy_patch.yaml
Fix the verbosity arguments
Fixes #
=> ✨ Enable verbosity control

docs/users.md
This PR updates the user guide to have more/better information about the kubeconfig extension that holds the name of the hosting cluster context.
Fixes #
=> 📖 More better doc of hosting context extension

cmd/kflex/create/create.go, cmd/kflex/ctx/ctx.go, cmd/kflex/main.go, docs/users.md
This PR make `kflex ctx` print an error message and exit with non-zero status when it fails to do its job.
Fixes #253
=> 🐛 Expose failure to switch to hosting context

pkg/util/unstructured.go
fix IsClusterScoped function not correctly handling empty API group
Fixes #278
=> 🐛 fix IsClusterScoped function not correctly handling empty API group

cmd/kflex/create/create.go, cmd/kflex/ctx/ctx.go, cmd/kflex/delete/delete.go, cmd/kflex/main.go, docs/users.md, pkg/kubeconfig/config-util.go
Provides new flags for  the`kflex ctx` command:
- `--overwrite-existing-context`
- `--set-current-for-hosting`
to help with those cases where hosting cluster context stored in kubeconfig is invalid.
Fixes #288
=> ✨ more forceful kflex ctx commands

internal/controller/controlplane_controller.go
enqueue secrets created by vcluster in addition to owned secrets 
Fixes #2717
=> 🐛 enqueue secrets created by vcluster in addition to owned secrets

chart/templates/postgresql.yaml
KubeFlex chart was changed to use PostgreSQL chart stored in Quay.io: `oci://quay.io/kubestellar/charts/postgresq:13.1.5`
The chart is a copy of the original `oci://registry-1.docker.io/bitnamicharts/postgresql:13.1.5` but pointing to the container image in quay at `quay.io/kubestellar/postgresql/16.0.0-debian-11-r13` which is a multi-arch (amd64/arm64) copy of the original image at `docker.io/bitnami/postgresql:16.0.0-debian-11-r13`.
The main objective of this PR is to avoid hitting Docker pull request limit, especially during testing.
Fixes #
=> ✨ Use postgresql chart and image from quay.io

internal/controller/controlplane_controller.go, pkg/reconcilers/external/reconciler.go, pkg/reconcilers/host/reconciler.go, pkg/reconcilers/k8s/reconciler.go, pkg/reconcilers/ocm/reconciler.go, pkg/reconcilers/shared/ingress.go, pkg/reconcilers/shared/job.go, pkg/reconcilers/shared/namespace.go, pkg/reconcilers/shared/postcreate_hook.go, pkg/reconcilers/shared/rbac.go, pkg/reconcilers/shared/reconciler.go, pkg/reconcilers/shared/route.go, pkg/reconcilers/vcluster/chart.go, pkg/reconcilers/vcluster/reconciler.go, pkg/reconcilers/vcluster/service.go, pkg/util/unstructured.go, pkg/util/util.go
This PR fixes three issues.
1. Wrong reference to ControlPlane derived from vc-vcluster Secret.
2. Misuse of a global variable.
3. Logging gaps/bugs.
This PR also adds Event logging for ControlPlane sync results, which should be helpful in the case of transient syncing problems. Issue #318 has a transient sync failure that lasts for a highly variable amount of time. In particular, sometimes it is long enough to cause https://github.com/kubestellar/kubestellar/issues/2717 --- and yet be gone by the time someone investigates.
Fixes #318 
Fixes #322 
Fixes #321
=> 🐛  Fix sharing, enqueuing, and logging bugs

cmd/kflex/ctx/ctx.go, cmd/kflex/main.go, pkg/kubeconfig/kubeconfig.go
This PR adds a new subcommand `get` under the `ctx` command to retrieve and display the current context from the kubeconfig file. The changes include:
1. Added a new function `GetCurrentContext` in `pkg/kubeconfig/kubeconfig.go` to retrieve the current context.
2. Added a new method `GetCurrentContext` in `cmd/kflex/ctx/ctx.go` to handle the `get` subcommand.
3. Updated `main.go` to include the `get` subcommand under `ctxCmd`.
Fixes #165
=> :sparkles: Add kflex command/flag to get the current context

config/samples/postcreate-hooks/openshift-crds.yaml
This PR updates the container image reference in `openshift-crds.yaml` to use the organization registry (`quay.io/kubestellar`) instead of the personal account (`quay.io/pdettori`).
Changes made:
- Updated image path from `oci://quay.io/pdettori/openshift-crds` to `oci://quay.io/kubestellar/openshift-crds`
Fixes #216
=> ✨ feature: Move openshift-crds container image to quay.io/kubestellar registry

cmd/kflex/ctx/ctx.go, cmd/kflex/ctx/list.go, cmd/kflex/main.go, docs/users.md, pkg/kubeconfig/kubeconfig.go
This PR implements the `kflex ctx list` command to display all available contexts in the kubeconfig file, with the current context marked with an asterisk (*). The changes include:
1. Added new `ListContexts()` function in `pkg/kubeconfig/config-util.go`
2. Added new `GetCurrentContext()` helper function
3. Updated `cmd/kflex/ctx/ctx.go` to handle the list command
4. Added new command definition in `cmd/kflex/main.go`
5. Updated documentation in `docs/users.md`
The implementation follows existing patterns in the codebase and provides a clean, user-friendly way to view all available contexts.
Fixes #166
=> ✨ feature: Add kflex command to list available contexts

Makefile, cmd/kflex/adopt/adopt.go, cmd/kflex/common/cp.go, cmd/kflex/common/flags.go, cmd/kflex/create/create.go, cmd/kflex/ctx/ctx.go, cmd/kflex/ctx/get.go, cmd/kflex/ctx/list.go, cmd/kflex/delete/delete.go, cmd/kflex/init/cluster/kind.go, cmd/kflex/init/init.go, cmd/kflex/list/list.go, cmd/kflex/main.go, cmd/kflex/version/version.go, docs/debugging.md, docs/users.md, pkg/kubeconfig/kubeconfig.go
Before this PR, a couple of parameters, types and others have been copy paste and did not leverage the power that spf13/cobra offers (reusability, modularity...)
To solve this problem, I decided to change the codebase design at the `cmd/kflex/` level. 
For this proof of concept, **ONLY** the commands listed below have been refactored and the code as it is currently would not build.
- `kflex create`
- `kflex list`
Overall, the design change vows to:
- simplify the codeflow which will make the OSS adoption by contributors easier
- avoid side-effects as much as possible, which could explain the number of bugs reported
- improve readability of the codebase with better naming convention, remove unecessary struct/types, better semantic
- be more idiomatic. My references are [Learn Go the …
=> 🐛 refactoring and design change on the usage of spf13/cobra

docs/contributors.md
This PR updates the `contributors.md` file to include instructions for fetching tags from the upstream repository. As mentioned in issue #348, without these tags, commands like `kflex init -c` fail because version information is derived from git tags.
The changes:
- Added instructions to set up the upstream remote
- Added instructions to fetch tags from upstream
- Added a note explaining why fetching tags is important
These simple additions should help new contributors avoid the frustration of commands not working after following the guide.
Fixes #348
=> 🐛bug fix: Update contributors.md with instructions to fetch upstream tags

api/v1alpha1/postcreatehook_types.go, config/crd/bases/tenancy.kflex.kubestellar.org_postcreatehooks.yaml, config/samples/postcreate-hooks/hello.yaml, docs/users.md, pkg/reconcilers/shared/postcreate_hook.go
- Added `defaultVars` field to PostCreateHook API for defining default template variables
- Implemented variable resolution precedence: 
- System variables (Namespace/ControlPlaneName/HookName) have highest priority
- User-provided variables from ControlPlane override defaults
- PostCreateHook defaults serve as base values
- Updated CRD validation schema with new field
- Added documentation examples for variable usage
Fixes: #233
=> ✨ feature add default variables support for PostCreateHook

chart/templates/operator.yaml, go.mod, go.sum
To pick up security fixes.
This PR bumps two more dependencies, to pick up security fixes.
The chosen version of the kube-rbac-proxy is the latest one available that works with Kubernetes release 1.30. It has one critical vulnerability, https://github.com/advisories/GHSA-v778-237x-gjrc, and I am not sure it is exploitable in kube-rbac-proxy.
Fixes #
=> ✨  Bump kube-rbac-proxy image and golang.org/x/net package

pkg/reconcilers/shared/ingress.go, pkg/reconcilers/shared/job.go, pkg/reconcilers/shared/namespace.go, pkg/reconcilers/shared/postcreate_hook.go, pkg/reconcilers/shared/rbac.go, pkg/reconcilers/shared/route.go, pkg/reconcilers/vcluster/reconciler.go, pkg/reconcilers/vcluster/secret.go, pkg/reconcilers/vcluster/service.go, pkg/util/errors.go
This PR fixes error handling in multiple reconcilers to properly distinguish between transient and permanent errors. Transient errors (e.g., connection issues, timeouts) will now trigger automatic retries, while permanent errors will be logged without retry attempts.
Key changes:
1. Added `util.IsTransientError()` helper function
2. Modified error handling in namespace/ingress/route/service/RBAC/job reconcilers
3. Updated post-create hook error handling
4. Maintained existing status update patterns through controller return values
Fixes: #320
=> 🐛 add retry logic for transient API errors

cmd/kflex/common/flags.go, cmd/kflex/ctx/ctx.go, cmd/kflex/ctx/ctx_test.go, cmd/kflex/ctx/delete.go, cmd/kflex/ctx/delete_test.go, cmd/kflex/ctx/rename.go, cmd/kflex/ctx/rename_test.go, cmd/kflex/delete/delete.go, docs/users.md, pkg/kubeconfig/config-util.go, test/e2e/manage-ctx.sh
Proposal PR -- as issue is not yet accepted, the following solution is proposed to give details and working implementation
`kflex ctx delete` subcommand is now added to allow user removing orphans context (created during dev phase).
This command properly clean useless contexts and its cluster and user of the kubeconfig.
**Note:** in the continuity of #352 and its refactoring process, the following has been added to improve the codeflow:
- **Explicit naming to avoid confusion**. `kubeconfig.DeleteContext` is renamed to `kubeconfig.DeleteAll` as the method delete the triple **context,cluster,user** from the kubeconfig, not just the context as implied by the signature.
- **Better error handling**. Instead of abruptly stop the codeflow using
```
fmt.FPrintf(err) // first display error …
```
=> ✨ add kflex ctx delete command 

.github/workflows/test-e2e.yaml, chart/templates/operator.yaml, config/default/manager_auth_proxy_patch.yaml
This PR bumps the version of the quay.io/brancz/kube-rbac-proxy image used in the kubestellar-controller-manager Deployment from v0.18.0 to v0.19.1. The benefit is fewer security vulnerabilities. The downside is that v0.19.1 is built on Kubernetes 1.31, while the rest of KubeFlex uses Kubernetes 1.30. I suspect that this inconsistency will not be problematic because of the narrow job of this particular image.
Fixes #
=> ✨  Bump version of kube-rbac-proxy image from 0.18.0 to 0.19.1

cmd/kflex/common/flags.go, cmd/kflex/create/create.go, cmd/kflex/ctx/ctx.go, cmd/kflex/ctx/ctx_test.go, cmd/kflex/ctx/delete.go, cmd/kflex/ctx/rename.go, cmd/kflex/delete/delete.go, cmd/kflex/init/init.go, cmd/kflex/main.go, docs/users.md, pkg/kubeconfig/extensions.go, pkg/kubeconfig/extensions_test.go, pkg/kubeconfig/kubeconfig.go
The implementation of `Preferences` used to be *on-the-fly* by using `corev1.ConfigMap` as "k8s.io/client-go/tools/clientcmd/api" requires `runtime.Object` type for `Extension`.
In our new implementation, a new file `extensions.go` is created where structs are defined. This allow us Static typing and check at compilation time, reducing likelihood of errors.
Within the code, breaking changes are indicated through comment `// BREAKING CHANGE`
```go
const (
ExtensionConfigName                = "config-extension-name"    // BREAKING CHANGE
ExtensionHostingClusterContextName = "hosting-cluster-ctx-name" // BREAKING CHANGE
```
Those values have changed. Also, perhaps some of these values are now useless. In fact, all kubeflex metadata are stored under `kubeflex` key (ie. `extensions.kubeflex`) …
=> ✨ Usage of Extensions

cmd/kflex/config/config.go, cmd/kflex/config/config_test.go, cmd/kflex/config/set_hosting_cluster_ctx.go, cmd/kflex/config/set_hosting_cluster_ctx_test.go, cmd/kflex/ctx/ctx_test.go, cmd/kflex/ctx/delete_test.go, cmd/kflex/ctx/rename_test.go, cmd/kflex/list/list.go, cmd/kflex/main.go, docs/users.md, pkg/kubeconfig/extensions.go, pkg/kubeconfig/kubeconfig.go
Introducing `kflex config` command to interact with kubeconfig/kubeflex configuration.
This PR introduces the first config feature `set-hosting` to set/change the value of hosting cluster context name.
**Usage:** `kflex config set-hosting $mycp` 
Set hosting cluster context name to `$mycp` value
Fixes #387
=> ✨ Add `kflex config set-hosting`

.github/workflows/ci.yaml, .github/workflows/dco.yaml, .github/workflows/test-e2e.yaml, api/v1alpha1/controlplane_types.go, pkg/reconcilers/k3s/README.md, pkg/reconcilers/k3s/apiserver.go, pkg/reconcilers/k3s/reconciler.go, pkg/reconcilers/k3s/service.go, pkg/reconcilers/k8s/deployment.go, pkg/reconcilers/k8s/reconciler.go, pkg/reconcilers/shared/postcreate_hook.go, pkg/reconcilers/shared/reconciler.go, pkg/reconcilers/shared/route.go, pkg/util/pg.go
Add skeleton for k3s reconciler package.
A different code design has been chosen to implement k3s (!= vcluster or k8s).
Instead of defining multiple reconcile functions depending of a resource (ie. ReconcileNamespace, ReconcileService), a `ControlPlaneReconciler` interface is now defined. (NOTE: I wonder if it should be named `KubeflexReconciler` instead...) Based on that interface, k3s declares concrete types representing kubernetes components `Service` `APIServer` `Reconciler`. All these concrete types implement `ControlPlaneReconciler`. As a result, `K3sReconciler` is defined as follow
```go
// New code design
type K3sReconciler struct {
*Service               // k3s service
*APIServer             // k3s api server
*shared.BaseReconciler // shared base controller
}
```
instead of …
=> ✨: add k3s package for reconciler

pkg/reconcilers/k3s/apiserver.go, test/dev/k3stest.yaml
When k3s-server is deployed, the following error arise
`time="2025-06-24T14:56:41Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: mkdir /etc/rancher: read-only file system"`
To solve it, security context has been added at the container level to enable filesystem to be writeable by root. In addition, container must be ran privileged as shown on the official documentation: https://docs.k3s.io/advanced#using-docker-as-the-container-runtime
Now, `k3s-server` is running once deployed
```shell
└─[$] <git:(lxf/main*)> k get pods -n k3stest
NAME         READY   STATUS    RESTARTS   AGE
k3s-server   1/1     Running   0          81s
```
and its logs
```log
...
│ I0624 14:59:31.293305      58 event.go:389] "Event occurred" object="kube-system/traefik" fieldPath="" …
```
=> 🐛Lxf/431: solve k3s server pod error

pkg/kubeconfig/kubeconfig.go, pkg/kubeconfig/kubeconfig_test.go
The update to the `AssignControlPlaneToContext` function in the pkg/kubeconfig package ensures that the function now correctly stores the control plane name as an extension within the context's kubeflex extension data. This resolves the previously missing step where the control plane name was not being assigned to the extension. A new kubeconfig_test.go file is created to provide unit tests.
Fixes #435
=> ✨ feature : add control plane name to kubeflex extension data

pkg/kubeconfig/kubeconfig.go, pkg/kubeconfig/kubeconfig_test.go, test/e2e/manage-type-k8s.sh, test/e2e/manage-type-vcluster.sh
Ensures that `kflex create myhellocp --type=vcluster` assigns controlplane name within context-scope.
Update `test/e2e/manage-type-vcluster.sh`.
Fixes #437
=> 🌱 test: update vcluster e2e test for changes in AssignControlPlaneToContext

pkg/kubeconfig/extensions.go, pkg/kubeconfig/extensions_test.go
Create 3 tests for CheckGlobalKubeflexExtension for the following cases : 
1. Extension is not set
2. Extension is set but empty
3. Extension is set
Note : This PR should be reviewed after #456 
redpinecube/kubeflex#8
Relates to #388
=> 🌱 test : CheckGlobalKubeflexExtension

cmd/kflex/config/config.go, cmd/kflex/config/diagnose.go, pkg/kubeconfig/extensions.go, pkg/kubeconfig/extensions_test.go
Implement the initial version of `kflex config diagnose` to check if the global kubeflex extension is set. 
Note : This PR should be reviewed after #457 
redpinecube/kubeflex#9
Relates to #388
=>  ✨ feature : implement initial kflex config diagnose

cmd/kflex/create/create.go, pkg/reconcilers/k3s/reconciler.go, pkg/reconcilers/k3s/secret.go, pkg/reconcilers/k3s/service.go
Add k3s secret reconciler to create:
- k3s kubeconfig secret
- k3s in-cluster kubeconfig secret
Although the k3s secret is successfully created, there is no value on k3s kubeconfig offcluster. How to retrieve that? 
Fixes #444
=> ✨new: add k3s secret config and in-cluster config

pkg/kubeconfig/extensions.go, pkg/kubeconfig/extensions_test.go
Testing ensures `CheckHostingClusterContextName` returns a `critical` status when no context is marked as a hosting cluster. Originally, this function depended on `CheckGlobalKubeflexExtension`, but it's preferable to remove that dependency to diagnose all potential issues collectively, rather than one at a time.
redpinecube/kubeflex#14
#388
=> 🌱 test & update : CheckHostingClusterContextNameNone

pkg/kubeconfig/extensions.go, pkg/kubeconfig/extensions_test.go
Test that `CheckHostingClusterContextName` returns `DiagnosisStatusOK` when there is a single hosting cluster context name set in the config. 
Note : Please review this PR after #464  
redpinecube/kubeflex#16
#388
=> 🌱 test : CheckHostingClusterContextName with a single hosting cluster

cmd/kflex/ctx/ctx_test.go, cmd/kflex/ctx/delete.go, cmd/kflex/ctx/delete_test.go, cmd/kflex/ctx/rename.go, pkg/kubeconfig/kubeconfig.go, test/e2e/manage-ctx.sh
Summary :-
This PR implements a safety guard for the kflex ctx delete command to prevent accidental deletion of Kubernetes contexts not managed by KubeFlex.
Changes
•	Added IsContextManagedByKubeflex function to detect if a context is managed by KubeFlex.
•	Modified ExecuteCtxDelete to:
•	Display a warning if the context is not managed by KubeFlex.
•	Prompt the user for confirmation before deleting non-managed contexts.
•	Support a --force flag to bypass confirmation for automation.
•	Updated tests to cover both KubeFlex-managed and non-managed contexts.
closes #392
=> ✨ Add guard for kflex ctx delete: confirmation for non-KubeFlex contexts

pkg/kubeconfig/extensions.go
Implements `CheckContextScopeKubeflexExtensionSet` to check if the data and metadata for context-scope extensions are set correctly. If no extensions exist or if no kubeflex extensions exists, returns `DiagnosisStatusOK`
redpinecube/kubeflex#14
#388
=> ✨ feature : implement CheckContextScopeKubeflexExtensionSet

pkg/kubeconfig/extensions.go, pkg/kubeconfig/extensions_test.go
Tests that `CheckContextScopeKubeflexExtensionSet` returns a warning status with partial data.
Note : Please review this PR after #478 
redpinecube/kubeflex#20
#388
=> 🌱  test : CheckContextScopeKubeflexExtensionSet with partial data

cmd/kflex/ctx/list.go, pkg/kubeconfig/extensions_test.go, pkg/util/util.go, test/e2e/manage-ctx.sh
This PR enhances the `kflex ctx list` command to display additional information about KubeFlex-managed contexts, making it easier for users to identify which contexts are managed by KubeFlex and which control planes they are associated with.
Fixes #393
- **Before**: Simple list of contexts with current context indicator
```
Available Contexts:
cluster1
* cluster2
docker-desktop
testcp
```
- **After**: Tabular format with KubeFlex information
```
CONTEXT                        MANAGED BY KFLEX   CONTROLPLANE   
cluster1                                                       
* cluster2                                                       
docker-desktop                                                 
testcp                       yes                testcp         
```
=> ✨feature: enhance kflex ctx list with KubeFlex context information

pkg/reconcilers/k3s/apiserver.go, pkg/reconcilers/k3s/ingress.go, pkg/reconcilers/k3s/job.go, pkg/reconcilers/k3s/rbac.go, pkg/reconcilers/k3s/service.go
Before this PR, it was not possible to create 2 controlplanes of type k3s as they were sharing the common name for ingress and clusterrolebinding, putting the reconciling loop in error.
Now ingress and clusterrolebinding leverage controlplane name to their resource name.
Fixes #510
=> 🐛 ingress name and clusterrolebinding is attached to controlplane name

pkg/kubeconfig/extensions.go, pkg/kubeconfig/extensions_test.go
Implements logic to check if a control plane is actually on a hosting cluster for CheckContextScopeKubeflexExtensionSet. 
#388 
redpinecube/kubeflex#21
=> ✨feature : implement VerifyControlPlaneOnHostingCluster

.github/workflows/ci.yaml, .github/workflows/dco.yaml, .github/workflows/goreleaser.yml, .github/workflows/spellcheck_action.yml, .github/workflows/test-e2e.yaml
Bumps [actions/checkout](https://github.com/actions/checkout) from 4 to 5.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/actions/checkout/releases">actions/checkout's releases</a>.</em></p>
<blockquote>
<h2>v5.0.0</h2>
<h2>What's Changed</h2>
<ul>
<li>Update actions checkout to use node 24 by <a href="https://github.com/salmanmkc"><code>@​salmanmkc</code></a> in <a href="https://redirect.github.com/actions/checkout/pull/2226">actions/checkout#2226</a></li>
<li>Prepare v5.0.0 release by <a href="https://github.com/salmanmkc"><code>@​salmanmkc</code></a> in <a href="https://redirect.github.com/actions/checkout/pull/2238">actions/checkout#2238</a></li>
</ul>
<h2>⚠️ Minimum Compatible Runner Version</h2>
<p><strong>v2.327.1</strong><br />
<a …
=> 🌱 Bump actions/checkout from v4 to v5

cmd/kflex/ctx/ctx.go, pkg/kubeconfig/extensions.go, pkg/kubeconfig/extensions_test.go, pkg/kubeconfig/kubeconfig.go
Validate the kubeconfig kubeflex extension before switching: map legacy key for compatibility, ignore non-existent or cluster-less contexts, print a clear warning and fall back safely. Includes unit tests for valid, missing and malformed saved contexts.
Fixes #202
=> 🐛fix(kubeconfig): validate and ignore invalid saved hosting context, warn instead of failing

Makefile, chart/templates/install-hooks.yaml, chart/templates/namespace.yaml, docs/users.md
Change the Helm chart to ensure kubeflex-system ns existence.
This allows one to install the chart without previously creating the `kubeflex-system` or passing the `kubeflex-system` namespace on the helm CLI.
This change is backwards compatible with both:
```bash
kubectl create kubeflex-system
helm upgrade --install kubeflex-operator <chart>
```
and
```
helm upgrade --install kubeflex-operator -n kubeflex-system --create-namespace <chart>
```
Edited files:
- chart to add the new namespace template
- docs to remove the longer commands
- makefile
Fixes #541
=> ✨Change the Helm chart to ensure kubeflex-system ns existence
